import Foundation

struct SupportedLanguage: Identifiable, Hashable {
    let code: String
    let name: String
    let flag: String

    var id: String { code }

    /// All 99 Whisper-supported languages, English first, then alphabetical by name.
    static let all: [SupportedLanguage] = {
        let languages = [
            SupportedLanguage(code: "en", name: "English", flag: "🇬🇧"),
            SupportedLanguage(code: "af", name: "Afrikaans", flag: "🇿🇦"),
            SupportedLanguage(code: "am", name: "Amharic", flag: "🇪🇹"),
            SupportedLanguage(code: "ar", name: "Arabic", flag: "🇸🇦"),
            SupportedLanguage(code: "as", name: "Assamese", flag: "🇮🇳"),
            SupportedLanguage(code: "az", name: "Azerbaijani", flag: "🇦🇿"),
            SupportedLanguage(code: "ba", name: "Bashkir", flag: "🇷🇺"),
            SupportedLanguage(code: "be", name: "Belarusian", flag: "🇧🇾"),
            SupportedLanguage(code: "bg", name: "Bulgarian", flag: "🇧🇬"),
            SupportedLanguage(code: "bn", name: "Bengali", flag: "🇧🇩"),
            SupportedLanguage(code: "bo", name: "Tibetan", flag: "🇨🇳"),
            SupportedLanguage(code: "br", name: "Breton", flag: "🇫🇷"),
            SupportedLanguage(code: "bs", name: "Bosnian", flag: "🇧🇦"),
            SupportedLanguage(code: "ca", name: "Catalan", flag: "🇪🇸"),
            SupportedLanguage(code: "cs", name: "Czech", flag: "🇨🇿"),
            SupportedLanguage(code: "cy", name: "Welsh", flag: "🏴󠁧󠁢󠁷󠁬󠁳󠁿"),
            SupportedLanguage(code: "da", name: "Danish", flag: "🇩🇰"),
            SupportedLanguage(code: "de", name: "German", flag: "🇩🇪"),
            SupportedLanguage(code: "el", name: "Greek", flag: "🇬🇷"),
            SupportedLanguage(code: "es", name: "Spanish", flag: "🇪🇸"),
            SupportedLanguage(code: "et", name: "Estonian", flag: "🇪🇪"),
            SupportedLanguage(code: "eu", name: "Basque", flag: "🇪🇸"),
            SupportedLanguage(code: "fa", name: "Persian", flag: "🇮🇷"),
            SupportedLanguage(code: "fi", name: "Finnish", flag: "🇫🇮"),
            SupportedLanguage(code: "fo", name: "Faroese", flag: "🇫🇴"),
            SupportedLanguage(code: "fr", name: "French", flag: "🇫🇷"),
            SupportedLanguage(code: "gl", name: "Galician", flag: "🇪🇸"),
            SupportedLanguage(code: "gu", name: "Gujarati", flag: "🇮🇳"),
            SupportedLanguage(code: "ha", name: "Hausa", flag: "🇳🇬"),
            SupportedLanguage(code: "haw", name: "Hawaiian", flag: "🇺🇸"),
            SupportedLanguage(code: "he", name: "Hebrew", flag: "🇮🇱"),
            SupportedLanguage(code: "hi", name: "Hindi", flag: "🇮🇳"),
            SupportedLanguage(code: "hr", name: "Croatian", flag: "🇭🇷"),
            SupportedLanguage(code: "ht", name: "Haitian Creole", flag: "🇭🇹"),
            SupportedLanguage(code: "hu", name: "Hungarian", flag: "🇭🇺"),
            SupportedLanguage(code: "hy", name: "Armenian", flag: "🇦🇲"),
            SupportedLanguage(code: "id", name: "Indonesian", flag: "🇮🇩"),
            SupportedLanguage(code: "is", name: "Icelandic", flag: "🇮🇸"),
            SupportedLanguage(code: "it", name: "Italian", flag: "🇮🇹"),
            SupportedLanguage(code: "ja", name: "Japanese", flag: "🇯🇵"),
            SupportedLanguage(code: "jw", name: "Javanese", flag: "🇮🇩"),
            SupportedLanguage(code: "ka", name: "Georgian", flag: "🇬🇪"),
            SupportedLanguage(code: "kk", name: "Kazakh", flag: "🇰🇿"),
            SupportedLanguage(code: "km", name: "Khmer", flag: "🇰🇭"),
            SupportedLanguage(code: "kn", name: "Kannada", flag: "🇮🇳"),
            SupportedLanguage(code: "ko", name: "Korean", flag: "🇰🇷"),
            SupportedLanguage(code: "la", name: "Latin", flag: "🇻🇦"),
            SupportedLanguage(code: "lb", name: "Luxembourgish", flag: "🇱🇺"),
            SupportedLanguage(code: "ln", name: "Lingala", flag: "🇨🇩"),
            SupportedLanguage(code: "lo", name: "Lao", flag: "🇱🇦"),
            SupportedLanguage(code: "lt", name: "Lithuanian", flag: "🇱🇹"),
            SupportedLanguage(code: "lv", name: "Latvian", flag: "🇱🇻"),
            SupportedLanguage(code: "mg", name: "Malagasy", flag: "🇲🇬"),
            SupportedLanguage(code: "mi", name: "Maori", flag: "🇳🇿"),
            SupportedLanguage(code: "mk", name: "Macedonian", flag: "🇲🇰"),
            SupportedLanguage(code: "ml", name: "Malayalam", flag: "🇮🇳"),
            SupportedLanguage(code: "mn", name: "Mongolian", flag: "🇲🇳"),
            SupportedLanguage(code: "mr", name: "Marathi", flag: "🇮🇳"),
            SupportedLanguage(code: "ms", name: "Malay", flag: "🇲🇾"),
            SupportedLanguage(code: "mt", name: "Maltese", flag: "🇲🇹"),
            SupportedLanguage(code: "my", name: "Myanmar", flag: "🇲🇲"),
            SupportedLanguage(code: "ne", name: "Nepali", flag: "🇳🇵"),
            SupportedLanguage(code: "nl", name: "Dutch", flag: "🇳🇱"),
            SupportedLanguage(code: "nn", name: "Nynorsk", flag: "🇳🇴"),
            SupportedLanguage(code: "no", name: "Norwegian", flag: "🇳🇴"),
            SupportedLanguage(code: "oc", name: "Occitan", flag: "🇫🇷"),
            SupportedLanguage(code: "pa", name: "Punjabi", flag: "🇮🇳"),
            SupportedLanguage(code: "pl", name: "Polish", flag: "🇵🇱"),
            SupportedLanguage(code: "ps", name: "Pashto", flag: "🇦🇫"),
            SupportedLanguage(code: "pt", name: "Portuguese", flag: "🇵🇹"),
            SupportedLanguage(code: "ro", name: "Romanian", flag: "🇷🇴"),
            SupportedLanguage(code: "ru", name: "Russian", flag: "🇷🇺"),
            SupportedLanguage(code: "sa", name: "Sanskrit", flag: "🇮🇳"),
            SupportedLanguage(code: "sd", name: "Sindhi", flag: "🇵🇰"),
            SupportedLanguage(code: "si", name: "Sinhala", flag: "🇱🇰"),
            SupportedLanguage(code: "sk", name: "Slovak", flag: "🇸🇰"),
            SupportedLanguage(code: "sl", name: "Slovenian", flag: "🇸🇮"),
            SupportedLanguage(code: "sn", name: "Shona", flag: "🇿🇼"),
            SupportedLanguage(code: "so", name: "Somali", flag: "🇸🇴"),
            SupportedLanguage(code: "sq", name: "Albanian", flag: "🇦🇱"),
            SupportedLanguage(code: "sr", name: "Serbian", flag: "🇷🇸"),
            SupportedLanguage(code: "su", name: "Sundanese", flag: "🇮🇩"),
            SupportedLanguage(code: "sv", name: "Swedish", flag: "🇸🇪"),
            SupportedLanguage(code: "sw", name: "Swahili", flag: "🇰🇪"),
            SupportedLanguage(code: "ta", name: "Tamil", flag: "🇮🇳"),
            SupportedLanguage(code: "te", name: "Telugu", flag: "🇮🇳"),
            SupportedLanguage(code: "tg", name: "Tajik", flag: "🇹🇯"),
            SupportedLanguage(code: "th", name: "Thai", flag: "🇹🇭"),
            SupportedLanguage(code: "tk", name: "Turkmen", flag: "🇹🇲"),
            SupportedLanguage(code: "tl", name: "Tagalog", flag: "🇵🇭"),
            SupportedLanguage(code: "tr", name: "Turkish", flag: "🇹🇷"),
            SupportedLanguage(code: "tt", name: "Tatar", flag: "🇷🇺"),
            SupportedLanguage(code: "uk", name: "Ukrainian", flag: "🇺🇦"),
            SupportedLanguage(code: "ur", name: "Urdu", flag: "🇵🇰"),
            SupportedLanguage(code: "uz", name: "Uzbek", flag: "🇺🇿"),
            SupportedLanguage(code: "vi", name: "Vietnamese", flag: "🇻🇳"),
            SupportedLanguage(code: "yi", name: "Yiddish", flag: "🇮🇱"),
            SupportedLanguage(code: "yo", name: "Yoruba", flag: "🇳🇬"),
            SupportedLanguage(code: "yue", name: "Cantonese", flag: "🇭🇰"),
            SupportedLanguage(code: "zh", name: "Chinese", flag: "🇨🇳"),
        ]
        // English first, then alphabetical by name
        let english = languages.filter { $0.code == "en" }
        let rest = languages.filter { $0.code != "en" }.sorted { $0.name < $1.name }
        return english + rest
    }()
}
